apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: "${USER_ASSIGNED_CLIENT_ID}"
  name: app-openai-msi-sa

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    azure.workload.identity/use: "true"  # Required. Only pods with this label can use workload identity.
  name: java-aks-openai-msi
spec:
  serviceAccountName: app-openai-msi-sa
  containers:
    - image: ghcr.io/gmezan/java-aks-openai-msi:main
      name: java-aks-openai-msi
      env:
        - name: AZURE_OPENAI_ENDPOINT
          value: "${OPENAI_ENDPOINT}"
        - name: AZURE_OPENAI_MODEL
          value: "${OPENAI_MODEL}"
      resources: {}